[pytest]
addopts = -p no:cacheprovider --ignore-glob=pytest-cache-files-* --ignore-glob=tests/pytest-cache-files-*
norecursedirs = pytest-cache-files-* tests/pytest-cache-files-* __pycache__ .pytest_cache .tmp
